export const GET_MOVIES_REQUEST = 'movies/GET_MOVIES_REQUEST'
export const GET_MOVIES_SUCCESS = 'movies/GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAIL = 'movies/GET_MOVIES_FAIL'

export const GET_MORE_MOVIES_REQUEST = 'movies/GET_MORE_MOVIES_REQUEST'
export const GET_MORE_MOVIES_SUCCESS = 'movies/GET_MORE_MOVIES_SUCCESS'
export const GET_MORE_MOVIES_FAIL = 'movies/GET_MORE_MOVIES_FAIL'

export const SET_MOVIES = 'movies/SET_MOVIES'
